resolver: lts-9.14

packages:
  - .

extra-deps:
  - heist-1.0.1.1
  - map-syntax-0.2.0.2
  - xmlhtml-0.2.5.2

  # Shake dependency
  - purescript-0.11.7
  - git: https://github.com/purescript/psc-package.git
    commit: 9ef4cab35a3c02a662873c8bf24cf64b07371cd0
