resolver: lts-10.5

packages:
  - .

extra-deps:
  - ansi-terminal-0.6.3.1
  - Glob-0.8.0
  - heist-1.0.1.2
  - map-syntax-0.2.0.2
  - pipes-http-1.0.5
  - purescript-0.11.7
  - turtle-1.3.6
  - unix-compat-0.4.3.1

  - git: https://github.com/purescript/psc-package.git
    commit: 1ad7e4c2d7345066373ac05307208f279c325346
