resolver: lts-9.14

packages:
  - .

  # Shake build tool
  - location:
      git: https://github.com/purescript/psc-package.git
      commit: 9ef4cab35a3c02a662873c8bf24cf64b07371cd0
    extra-dep: true

extra-deps:
  - heist-1.0.1.1
  - map-syntax-0.2.0.2
  - xmlhtml-0.2.5.2

  # Shake build tools
  - purescript-0.11.6

  # Purescript dependencies
  - Glob-0.7.14
  - blaze-html-0.8.1.3
  - blaze-markup-0.7.1.1
  - gitrev-1.2.0
  - pipes-http-1.0.5
