version: 2
jobs:
  haskell-8.0.2:
    docker:
      - image: haskell:8.0.2
    steps:
      - run: stack --version

      - checkout

      - restore_cache:
          keys:
            - stack-8.0.2-v2-{{ arch }}-{{ .Branch }}-{{ checksum "tabletop-client.cabal" }}-{{ checksum "stack.yaml" }}
            - stack-8.0.2-v2-{{ arch }}-{{ .Branch }}-{{ checksum "tabletop-client.cabal" }}-
            - stack-8.0.2-v2-{{ arch }}-{{ .Branch }}-
      - restore_cache:
          keys:
            - stack-work-8.0.2-v1-{{ arch }}-{{ .Branch }}-{{ checksum "stack.yaml" }}-{{ .Revision }}
            - stack-work-8.0.2-v1-{{ arch }}-{{ .Branch }}-{{ checksum "stack.yaml" }}-
      - restore_cache:
          keys:
            - psc-package-v1-{{ arch }}-{{ .Branch }}-{{ checksum "psc-package.json" }}

      - run: stack build tabletop-client
      - run: stack build psc-package
      - run: stack build purescript
      - run: stack exec site

      - save_cache:
          key: stack-8.0.2-v2-{{ arch }}-{{ .Branch }}-{{ checksum "tabletop-client.cabal" }}-{{ checksum "stack.yaml" }}
          paths:
            - /root/.stack
      - save_cache:
          key: stack-work-8.0.2-v1-{{ arch }}-{{ .Branch }}-{{ checksum "stack.yaml" }}-{{ .Revision }}
          paths:
            - ".stack-work"
      - save_cache:
          key: psc-package-v1-{{ arch }}-{{ .Branch }}-{{ checksum "psc-package.json" }}
          paths:
            - ".psc-package"

workflows:
  version: 2
  ghc:
    jobs:
      - haskell-8.0.2
