version: 2
jobs:
  build:
    docker:
      - image: ubuntu:17.10
    steps:
      - run: apt update && apt install -y wget libtinfo-dev
      - run: wget -qO- https://get.haskellstack.org/ | sh
      - run: stack --version
      - checkout

      - restore_cache:
          keys:
            - stack-v1-ghc-8.2.2-{{ arch }}-{{ .Branch }}-{{ .Revision }}
            - stack-v1-ghc-8.2.2-{{ arch }}-{{ .Branch }}
            - stack-v1-ghc-8.2.2-{{ arch }}
      - restore_cache:
          keys:
            - psc-package-v1-{{ checksum "psc-package.json" }}-{{ arch }}-{{ .Branch }}-{{ .Revision }}
            - psc-package-v1-{{ checksum "psc-package.json" }}-{{ arch }}-{{ .Branch }}
            - psc-package-v1-{{ checksum "psc-package.json" }}-{{ arch }}

      - run: stack build --fast --pedantic tabletop-client
      - run: stack build --fast --pedantic psc-package
      - run: stack build --fast --pedantic purescript
      - run: stack exec site

      - save_cache:
          key: stack-v1-ghc-8.2.2-{{ arch }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/.stack"
      - save_cache:
          key: psc-package-v1-{{ checksum "psc-package.json" }}-{{ arch }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".psc-package"
